debug: true

build:
  image: gcc:4.8
  environment:
    - DEBIAN_FRONTEND=noninteractive
  commands:
    - pwd
    - echo $DRONE_REPO
    - echo $DRONE_BRANCH
    - echo $DRONE_COMMIT
    - echo $DRONE_DIR
    - ./configure
    - make
    - make test

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
