debug: true

build:
  #image: fracting/msys32-docker:latest
  image: fracting/msys32-docker
  environment:
    - DEBIAN_FRONTEND=noninteractive
  commands:
    - pwd
    - echo $DRONE_REPO
    - echo $DRONE_BRANCH
    - echo $DRONE_COMMIT
    - echo $DRONE_DIR
    - ls /usr/bin
    - msys2-shell -c echo hello drone

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
