build:
  image: gcc:4.8
  environment:
    - DEBIAN_FRONTEND=noninteractive
  commands:
    - ./configure
    - make
    - make test

notify:
  irc:
    image: plugins/drone-irc
    prefix: build
    nick: drone
    channel: '#wine-zh'
    server:
      host: irc.oftc.net
      port: 6667
    on_started: true
