build:
  image: fracting/cygwin32
  shell: cygwin
  commands:
    - uname -a
    - ls /dev/fd
    - stat /dev/fd
    - pwd
    - ls -al

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
