build:
  image: fracting/msys32-docker
  command:
    - apt-get update -y
    - apt-get install -y attr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
