build:
  image: gcc:4.8
  environment:
    - DEBIAN_FRONTEND=noninteractive
  commands:
    - pwd
    - ./configure
    - make
    - make test

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
