build:
  image: fracting/msys32
  commands:
    - pwd
    - apt-get update -y
    - apt-get install -y attr
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

    - cd ..
    - pwd
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

    - cd ..
    - pwd
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

    - cd ..
    - pwd
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

    - cd ..
    - pwd
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

    - cd ..
    - pwd
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

    - cd ..
    - pwd
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

    - cd ~
    - pwd
    - touch testattr
    - setfattr -n user.hello -v world testattr
    - getfattr -n user.hello testattr

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
