debug: true

build:
  image: gcc:4.8
  command:
    - pwd
#    - gcc -v || true
    - echo $DRONE_REPO
    - echo $DRONE_BRANCH
    - echo $DRONE_COMMIT
    - echo $DRONE_DIR
    - echo $HOME
    - echo $USER
#    - ls ~/.wine || true
    - wine --version
    - ls /usr/bin
    - msys2-shell -c echo hello drone 
    - false


notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
