os:
  - linux

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-i686
  - sudo apt-get install -y wine1.7

language: c

compiler:
  - gcc

script:
  - make -f win32/Makefile.gcc
  - wine example.exe
  - wine minigzip.exe -d foo.gz
  - wine example_d.exe
  - wine minigzip_d.exe -d foo.gz
  - wine minigzip.exe foo
  - wine minigzip_d.exe -d foo.gz
  - wine minigzip_d.exe foo
  - wine minigzip.exe -d foo.gz
